# Generated by Django 6.0 on 2025-12-31 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='baby/', verbose_name='Фотография')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memories/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='text',
            field=models.TextField(verbose_name='Текст воспоминания'),
        ),
    ]
