# Generated by Django 6.0 on 2025-12-31 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love_site', '0002_babyphoto_delete_photo_alter_memory_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='our_photos/', verbose_name='Фотография')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Наше фото',
                'verbose_name_plural': 'Наши фото',
            },
        ),
    ]
